---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
framework_version: 3.0.3
serverless_language: ''
polling_url: https://trmnl.com/analytics.json
polling_headers: authorization=Bearer%20{{trmnl_api_key}}
polling_body: ''
id: 286220
custom_fields:
- keyname: author_bio
  name: About This Plugin
  field_type: author_bio
  category: analytics
  description: Allows plugin authors to monitor their plugins
  github_url: https://github.com/stephenyeargin/trmnl-plugin-analytics
  learn_more_url: https://trmnl.com/analytics
  email_address: stephen@yearg.in
- keyname: trmnl_api_key
  field_type: password
  name: TRMNL API Key
  description: Go to Account > User API Key
  placeholder: user_abcdef123456
- keyname: sort_by
  field_type: select
  name: Sort Table By
  description: How you want to sort the plugin table, unhealthy plugins always shown first
  options:
  - Alphabetically by name (A-Z): alpha
  - Count of installs (descending): install
  - Count of forks (descending): forks
  - Count of connections (forks + installs, descending): connections
  default: connections
name: TRMNL Plugin Analytics
refresh_interval: 120
